const fs = require('fs');

let content = fs.readFileSync('app/docente/planillas/PlanillasClient.tsx', 'utf8');

// Replace all specific known corrupted spots
const replacements = [
  // Headers and comments
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Interfaces \uFFFD[^\n]*/g, to: '// ─── Interfaces ──────────────────────────────────────────────────────────' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Helpers \uFFFD[^\n]*/g, to: '// ─── Helpers ─────────────────────────────────────────────────────────────' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Main Component \uFFFD[^\n]*/g, to: '// ─── Main Component ──────────────────────────────────────────────────────' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Selector state \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Selector state ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Sync Helper for URL & LocalStorage \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Sync Helper for URL & LocalStorage ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Restore from localStorage on mount if URL parameters were absent \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Restore from localStorage on mount if URL parameters were absent ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Data state \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Data state ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Grades grid state \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Grades grid state ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Weights edit state \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Weights edit state ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Portal mount guard \(SSR-safe\) \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Portal mount guard (SSR-safe) ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Add column modal \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Add column modal ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Resource linking in modal \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Resource linking in modal ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Edit modal \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Edit modal ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Toggle active \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Toggle active ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Delete confirm \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Delete confirm ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Manual Grading Full-Screen State \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Manual Grading Full-Screen State ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Duplication \/ Cloning Modal State \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Duplication / Cloning Modal State ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Reusable tasks for Add Modal \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Reusable tasks for Add Modal ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Exam \/ Task Management Modal \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Exam / Task Management Modal ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Custom Excel Sync Wizard State \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Custom Excel Sync Wizard State ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Derived \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Derived ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD URL Query Param watcher[^\n]*/g, to: '// ─── URL Query Param watcher for calificarTaskId persistence across F5 ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Category slices \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Category slices ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Cell handler \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Cell handler ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Save grades \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Save grades ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Save weight percentages \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Save weight percentages ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Add column \uFFFD \uFFFD\uFFFD \uFFFD/g, to: '// ─── Add column ───' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Excel export [^\n]*/g, to: '// ─── Excel export (Institutional Monsenor Diaz Plata Grade Sheet) ───' },
  { from: /\/\/ INSTITUCI\uFFFD N/g, to: '// INSTITUCIÓN' },
  { from: /\/\/ Category header row \(row 6\) \uFFFD  "No\." and "NOMBRE" span 2 rows/g, to: '// Category header row (row 6) — "No." and "NOMBRE" span 2 rows' },
  { from: /\/\/ DESEMPE\uFFFD O spans 2 rows/g, to: '// DESEMPEÑO spans 2 rows' },
  { from: /doc\.text\(`Consolidado \uFFFD  \$\{selectedCourse\?\.name \?\? ""\}/g, to: 'doc.text(`Consolidado — ${selectedCourse?.name ?? ""}' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Render helpers[^\n]*/g, to: '// ─── Render helpers ──────────────────────────────────────────────────────' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Full-Screen Manual Grading View[^\n]*/g, to: '// ─── Full-Screen Manual Grading View ────────────────────────────────────' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Full-Page Task \/ Exam Management View[^\n]*/g, to: '// ─── Full-Page Task / Exam Management View ──────────────────────────────' },
  { from: /\/\/ \uFFFD \uFFFD\uFFFD \uFFFD Main render[^\n]*/g, to: '// ─── Main render ─────────────────────────────────────────────────────────' },
  { from: /\{\/\* \uFFFD \uFFFD\uFFFD \uFFFD Fallback wizard[^\n]*/g, to: '{/* ─── Fallback wizard: only shown when auto-detection couldn\'t find student column ─── */}' },
  { from: /\{\/\* \uFFFD \uFFFD\uFFFD \uFFFD Sync Confirm Modal \(portal \uFFFD   escapes overflow:hidden\) \uFFFD \uFFFD\uFFFD \uFFFD \*\/\}/g, to: '{/* ─── Sync Confirm Modal (portal — escapes overflow:hidden) ─── */}' },
  { from: /\{\/\* \uFFFD \uFFFD\uFFFD \uFFFD Sync Result Modal \(portal \uFFFD   escapes overflow:hidden\) \uFFFD \uFFFD\uFFFD \uFFFD \*\/\}/g, to: '{/* ─── Sync Result Modal (portal — escapes overflow:hidden) ─── */}' },
  { from: /\{\/\* \uFFFD \uFFFD\uFFFD \uFFFD Duplicate \/ Clone Task Modal \uFFFD \uFFFD\uFFFD \uFFFD \*\/\}/g, to: '{/* ─── Duplicate / Clone Task Modal ─── */}' },
  { from: /0\uFFFD  A, 25\uFFFD  Z, 26\uFFFD  AA ⬦/g, to: '0 → A, 25 → Z, 26 → AA …' },
  
  // Specific UI string fixes
  { from: /`Grado \$\{activeGradeName\} \uFFFD  Grupo \$\{activeGroupName\}`/g, to: '`Grado ${activeGradeName} — Grupo ${activeGroupName}`' },
  { from: /\{catInfo\.label\} \{catInfo\.sublabel \? `\uFFFD  \$\{catInfo\.sublabel\}` : ""\}/g, to: '{catInfo.label} {catInfo.sublabel ? `— ${catInfo.sublabel}` : ""}' },
  { from: /\uFFFDx\}\s+\{groupGradeBadge\}/g, to: '🎓 {groupGradeBadge}' },
  { from: /¡Guardado con \uFFFD0xito!/g, to: '¡Guardado con éxito!' },
  { from: /<th className="py-3\.5 px-6 w-44 text-center whitespace-nowrap">Calificación \(1\uFFFD 5\)<\/th>/g, to: '<th className="py-3.5 px-6 w-44 text-center whitespace-nowrap">Calificación (1–5)</th>' },
  { from: /placeholder="\uFFFD "/g, to: 'placeholder="—"' },
  { from: /: "x  ️ Asignar Prórroga a Varios Estudiantes"\}/g, to: ': "📅 Asignar Prórroga a Varios Estudiantes"}' },
  { from: /: "\uFFFDx  ️ Asignar Prórroga a Varios Estudiantes"\}/g, to: ': "📅 Asignar Prórroga a Varios Estudiantes"}' },
  { from: /Abrir en Drive \uFFFD\s*/g, to: 'Abrir en Drive ↗' },
  { from: /`\$\{g\.grade\.name\} \uFFFD  \$\{g\.name\}`/g, to: '`${g.grade.name} — ${g.name}`' },
  { from: /\{ label: "Asignatura",\s+value: selectedCourse\?\.name \?\? "\uFFFD " \},/g, to: '{ label: "Asignatura",   value: selectedCourse?.name ?? "—" },' },
  { from: /\{student\.group\.grade\?\.name\} \uFFFD  \{student\.group\.name\}/g, to: '{student.group.grade?.name} — {student.group.name}' },
  { from: /\{\/\* Final \uFFFD  same color scale as Desempeño \*\/\}/g, to: '{/* Final — same color scale as Desempeño */}' },
  { from: /<span className="text-gray-400 font-bold">\uFFFD <\/span>/g, to: '<span className="text-gray-400 font-bold">—</span>' },
  { from: /: "\uFFFD "\}/g, to: ': "—"}' },
  { from: /Directorio de Evaluaciones \uFFFD  \{selectedPeriod\}/g, to: 'Directorio de Evaluaciones — {selectedPeriod}' },
  { from: /"SABER \uFFFD  Tarea"/g, to: '"SABER — Tarea"' },
  { from: /"SABER \uFFFD  Examen"/g, to: '"SABER — Examen"' },
  { from: /` \uFFFD  \$\{cat\.sublabel\}`/g, to: '` — ${cat.sublabel}`' },
  { from: /\uFFFDx \uFFFD Entrega en clase/g, to: '🏫 Entrega en clase' },
  { from: /\uFFFDx \uFFFD Entrega en plataforma/g, to: '💻 Entrega en plataforma' },
  { from: /"Visible para alumnos \uFFFD  clic para ocultar"/g, to: '"Visible para alumnos — clic para ocultar"' },
  { from: /"Oculto para alumnos \uFFFD  clic para activar"/g, to: '"Oculto para alumnos — clic para activar"' },
  { from: /\uFFFDS\uFFFD Crear Desde Cero/g, to: '✨ Crear Desde Cero' },
  { from: /\uFFFDx 9 Clonar \/ Reutilizar Existente/g, to: '📋 Clonar / Reutilizar Existente' },
  { from: /\uFFFDx \uFFFD <strong>Clonación Limpia:<\/strong>/g, to: '💡 <strong>Clonación Limpia:</strong>' },
  { from: /\{t\._count\?\.questions > 0 && ` ⬢ \uFFFDx \uFFFD \$\{t\._count\.questions\} preguntas`\}/g, to: '{t._count?.questions > 0 && ` ⬢ 📝 ${t._count.questions} preguntas`}' },
  { from: /\uFFFDx\s+Tarea \/ Taller \(Saber\)/g, to: '📝 Tarea / Taller (Saber)' },
  { from: /\uFFFDx \uFFFD Examen en Línea \(Saber\)/g, to: '🧠 Examen en Línea (Saber)' },
  { from: /\{\/\* Row 4 & Checkboxes \uFFFD  hidden for SER \*\/\}/g, to: '{/* Row 4 & Checkboxes — hidden for SER */}' },
  { from: /"Descripci\uFFFDn \(Opcional\)"/g, to: '"Descripción (Opcional)"' },
  { from: /"Descripci\uFFFDn del Examen"/g, to: '"Descripción del Examen"' },
  { from: /"Descripci\uFFFDn \/ Instrucciones de la Tarea"/g, to: '"Descripción / Instrucciones de la Tarea"' },
  { from: /"Ej\. Criterios de evaluaci\uFFFDn actitudinal\.\.\."/g, to: '"Ej. Criterios de evaluación actitudinal..."' },
  { from: /"Escribe las instrucciones aqu\uFFFD\.\.\."/g, to: '"Escribe las instrucciones aquí..."' },
  { from: /\uFFFDx \} Guía adjunta actual/g, to: '📎 Guía adjunta actual' },
  { from: /<span className="text-base">\uFFFDx 9<\/span> ¿En qué fila están/g, to: '<span className="text-base">1️⃣</span> ¿En qué fila están' },
  { from: /<span className="text-base">\uFFFDx \uFFFD<\/span> ¿Cuál columna tiene/g, to: '<span className="text-base">2️⃣</span> ¿Cuál columna tiene' },
  { from: /<span>\uFFFDS&<\/span> Notas nuevas a agregar/g, to: '<span>✅</span> Notas nuevas a agregar' },
  { from: /<span>\uFFFDx\s+<\/span> Notas ya existentes/g, to: '<span>🔒</span> Notas ya existentes (no se tocan)' },
  { from: /<span>\uFFFDa\uFFFD️<\/span> Estudiantes sin coincidencia/g, to: '<span>⚠️</span> Estudiantes sin coincidencia' },
  { from: /<span>\uFFFDx \uFFFD<\/span> Recuerda hacer clic en/g, to: '<span>💡</span> Recuerda hacer clic en' },
  { from: /<span className="text-xs font-semibold text-gray-700 dark:text-gray-300">\uFFFDx \uFFFD Estudiantes encontrados<\/span>/g, to: '<span className="text-xs font-semibold text-gray-700 dark:text-gray-300">👥 Estudiantes encontrados</span>' },
  { from: /<span className="text-xs font-semibold text-emerald-700 dark:text-emerald-400">\uFFFDS& Notas nuevas agregadas<\/span>/g, to: '<span className="text-xs font-semibold text-emerald-700 dark:text-emerald-400">✅ Notas nuevas agregadas</span>' },
  { from: /<span className="text-xs font-semibold text-slate-600 dark:text-slate-400">\uFFFDx\s+Notas existentes protegidas<\/span>/g, to: '<span className="text-xs font-semibold text-slate-600 dark:text-slate-400">🔒 Notas existentes protegidas</span>' },
  { from: /\uFFFDx \uFFFD Haz clic en <strong>&quot;Guardar&quot;<\/strong> para confirmar los cambios\./g, to: '💡 Haz clic en <strong>&quot;Guardar&quot;</strong> para confirmar los cambios.' },
  { from: /Entendido \uFFFDS\s*/g, to: 'Entendido ✓' },
  { from: /\uFFFDx \uFFFD <strong>Actividad Original:<\/strong>/g, to: '💡 <strong>Actividad Original:</strong>' },
  { from: /placeholder=\{!isSelected \? "Activa la casilla para escribir observación⬦" : "Comentario u observación opcional para el estudiante⬦"\}/g, to: 'placeholder={!isSelected ? "Activa la casilla para escribir observación..." : "Comentario u observación opcional para el estudiante..."}' }
];

for (const r of replacements) {
  content = content.replace(r.from, r.to);
}

fs.writeFileSync('app/docente/planillas/PlanillasClient.tsx', content, 'utf8');
console.log('Fixed PlanillasClient.tsx');
